### ISSUE TITLE
Add color

### ISSUE THREAD

**Issue by usergenic** [Polymer/tattoo#43]
Low priority perhaps, but colored output can brighten your day and call out status.

**Comment by FredKSchott** [comment]
🌞

**Comment by usergenic** [comment]
🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 
It's fixed
🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈
